### ISSUE TITLE
zone numbers must be sequential

### ISSUE THREAD

**Issue by bstabler** [UDST/activitysim#103]
ActivitySim assumes model zones (TAZs) are sequentially numbered from 1 to the max number of zones and that external zone numbers are after internal zone numbers.  This is required by Cube and is therefore how MTC TM1 is setup.  This will need to be revised since many regions and other modeling software platforms skip zones, use zone labels, and have external zone numbers before internal zone numbers.  This is somewhat related to the fact that ActivitySim eventually needs to support multiple zone systems as well.

**Comment by bstabler** [comment]
This will likely be fixed by [Multiple Zone Systems Design](https://github.com/UDST/activitysim/wiki/Multiple-Zone-Systems-Design)

**Comment by bstabler** [comment]
This won't be fixed with the multiple zone system design, but it will be prototyped.

**Comment by toliwaga** [comment]
fixed in #165
