### ISSUE TITLE
pytables 3.3.0 breaks openmatrix breaks activitysim

### ISSUE THREAD

**Issue by toliwaga** [UDST/activitysim#123]
Version 3.3.0 of pytables expired deprecated camelCase function names in favor of underscore_delimited names thus breaking references in openmatrix to getNode (now renamed get_node).

I updated the travis test script to require pytables=3.2.3.1 until openmatrix is updated to the new function names.

I also updated setup.py to `require tables >= 3.1.0, <3.3.0` 

but the current situation may present problems to anyone attempting to install activitysim via conda until openmatrix is updated.

Once that happens, the version restrictions should be removed from setup.py and .travis.yml

**Comment by toliwaga** [comment]
I submitted a pull request for a fix for this: osPlanning/omx#27

**Comment by bstabler** [comment]
@toliwaga to update activitysim to work with latest dev version of openmatrix
