### ISSUE TITLE
change example sample sizes

### ISSUE THREAD

**Issue by bstabler** [UDST/activitysim#158]
MTC TM1 sample sizes are 30.

#-- The following 5 parameters specify the sample size for location choice models
UsualWorkAndSchoolLocationChoice.SampleOfAlternatives.SampleSize         = 30
JointTourLocationChoice.SampleOfAlternatives.SampleSize                  = 30
IndividualNonMandatoryTourLocationChoice.SampleOfAlternatives.SampleSize = 30
AtWorkSubtourLocationChoice.SampleOfAlternatives.SampleSize              = 30
StopLocationSoa.SampleSize                                               = 30

**Comment by toliwaga** [comment]
How about for other interaction_simulate sample sizes?

For the scheduling models (mandatory_scheduling and non_mandatory_scheduling) it is tdd_alts that are being sampled. These are currently also set to 50

**Comment by bstabler** [comment]
The TM1 scheduling models use all the alternatives defined in config/tour_departure_and_duration_alternatives.csv.  There is no sampling.  

@toliwaga  - I assume you are referring to the sample_size argument in vector_tour_scheduling.py?  If so, then this needs to be removed.
