### ISSUE TITLE
PMC Chair Election

### ISSUE THREAD

**Issue by danielsclint** [UDST/activitysim#184]
With the creation of a governance document, we need a chair of the PMC. The San Francisco County Transportation Authority (SFCTA) and its representative @joecastiglione  have been nominated to chair the PMC through June 30, 2018.

Please cast a vote supporting or rejecting SFCTA as the first chair of the PMC.

This vote is of the PMC members.

**Comment by danielsclint** [comment]
+1 San Diego Association of Governments

**Comment by guyrousseau** [comment]
+1, Atlanta Regional Commission

**Comment by lmz** [comment]
+1, MTC

**Comment by joecastiglione** [comment]
+1, SFCTA

**Comment by stefancoe** [comment]
+1, PSRC

**Comment by bstabler** [comment]
The [Governance Page](https://github.com/UDST/activitysim/wiki/Governance) has been updated.
