### ISSUE TITLE
skims management

### ISSUE THREAD

**Issue by fscottfoti** [UDST/activitysim#32]
One thing we will eventually need is to pass in some sort of skims management rather then individual skims like we do [here](https://github.com/synthicity/activitysim/blob/master/activitysim/defaults/models/workplace_location.py#L59])

We definitely should not have to change the parameters to the model in order to add a new skim.  Really that's easy enough to do though - the easiest thing is probably to use wrap up a dictionary of key value pairs where keys are the name of the skim and values are the 2D matrix (in dense form) or 1D matrix (in sparse form).  This is already being done [here](https://github.com/synthicity/activitysim/blob/master/activitysim/defaults/models/workplace_location.py#L65) but we should move this into a Pythonic object or even just an injectable.

It's also possible we could represent skims as a data frame like this and use `merge` and `take` directly...

| Index  | AM_TT  | PM_TT  |
|---|---|---|
| (0,0)  | 5  | 4  |
| (0, 1)  | 10  | 8  |
| etc  | ...  | ... |

**Comment by e-lo** [comment]
My vote is for a readable pythonic object so long as it doesn't become cumbersome to implement.

Maybe throw it is in the `/tables` directory?

We have a rudimentary set of skim classes in SF-CHAMP that have code such as:

    TABLE_NUMBER_TO_NAME = {1:"LIVT", 2:"RIVT", 3:"MIVT", 4:"PIVT", 5:"FIVT", 6:"BIVT", 
                            7:"ACC_TIME", 8:"EGR_TIME", 9:"ACC_DIST", 10:"EGR_DIST",
                            11:"IWAIT", 12:"XWAIT", 
                            13:"TrDIST", 14:"DrDIST", 
                            15:"FUNTIME", 16:"XWKTIME", 17:"NUM_LINKS", 18:"TOT_FARE",
                            19:"ACCNODE", 20:"EGRNODE"}
    
    TABLE_NAME_TO_NUMBER = dict((v,k) for k, v in TABLE_NUMBER_TO_NAME.iteritems())
    
    #: All variables returned
    ALL_VARS = TABLE_NUMBER_TO_NAME.values()
    ALL_VARS.append("TOT_TIME")
    
    #: Skims related to time (for converting hundredths of mins to mins)
    TIME_SKIMS = ["LIVT", "RIVT", "MIVT", "PIVT", "FIVT", "BIVT",
                  "ACC_TIME", "EGR_TIME", "IWAIT", "XWAIT", "FUNTIME", "XWKTIME"]
    #: Skims related to distances (for converting hundredths of miles to miles)
    DIST_SKIMS = ["TrDIST", "DrDIST", "ACC_DIST", "EGR_DIST"]
    #: Skims related to cost
    FARE_SKIMS = ["TOT_FARE"]

Not ideal, but it was the one place we had to make changes if our skims changed.

**Comment by fscottfoti** [comment]
I was thinking of something very similar to this - @jiffyclub can put something like this together once we get the free cycles.

**Comment by guyrousseau** [comment]
Regarding skims management, something to keep in mind:  Over time, as a few of us are integrating our ABMs with DTA (dynamic traffic assignment), eventually skims will be replaced with accumulated individual  trajectories and sub-trajectories mining, via TDSP (time dependent shortest path), though we're still a couple of years away from accomplishing that.
