### ISSUE TITLE
Bug in female column calculation in persons table

### ISSUE THREAD

**Issue by bhargavasana** [UDST/activitysim#57]
In persons.py it is currently:
@orca.column("persons")
def female(persons):
    return persons.sex == 1

It should be:
@orca.column("persons")
def female(persons):
    return persons.sex == **2**

**Comment by fscottfoti** [comment]
Whoops!  Do you want to issue a pull request with that fix? (I can certainly do it but it might be good to get in the habit of contributing PRs ;)

**Comment by bhargavasana** [comment]
Sure, I will go ahead and fork this so that I can submit PRs.

**Comment by toliwaga** [comment]
This has already been fixed in master.
