### ISSUE TITLE
Getting Started Tutorial

### ISSUE THREAD

**Issue by danielsclint** [UDST/activitysim#60]
It may be best to amend the [documentation](https://udst.github.io/activitysim/) that @fscottfoti started writing last year.

**Comment by bstabler** [comment]
- We will start with Fletcher's website material (in the docs folder) and use the same github pages solution
- Will focus on a model user and will use the included example
- Will not require the user to modify stuff in activitysim
- A second "developer" tutorial will be a deeper dive into modifications for new modules, etc.

**Comment by danielsclint** [comment]
In [3/25/2016 meeting notes](https://github.com/UDST/activitysim/wiki/Project-Meeting-%282016%5C03%5C25%29), @bstabler indicated he would begin writing the example section for ActivitySim. This is the ticket for that action item.

**Comment by bstabler** [comment]
The current documentation tree is:

index
  - gettingstarted
  - core
  - skim
  - cdap
  - mnl
  - util

I'm working on extending it as follows:

index
  - gettingstarted
     - installation
     - installation
     - installation
     - installation
  - core
  - skim
  - cdap
  - mnl
  - util

**Comment by bstabler** [comment]
In order to make the example as comprehensive as possible, I merged in the trip mode choice running on the tours table for eatout purpose only branch, and then added it to simulation.py.  I also turned on the cdap model and reduced the household sample size to 1000 in order to run cdap with less than 16GB of RAM (#74).

**Comment by bstabler** [comment]
The draft documentation updates are now live for review - https://udst.github.io/activitysim.

**Comment by bstabler** [comment]
I made some significant updates to the wiki as well - https://github.com/UDST/activitysim/wiki

**Comment by danielsclint** [comment]
I like the level of effort to go through these items thoroughly. SANDAG will be putting someone on the the Getting Started tutorial the week of April 25.

**Comment by danielsclint** [comment]
On the Progress Report Phase 2 page in the wiki, @bstabler downgraded the progress in a lot of areas. @wusun2, please review to ensure you agree. Thanks.
