### ISSUE TITLE
Coveralls Testing via Continuous Integration System

### ISSUE THREAD

**Issue by danielsclint** [UDST/activitysim#62]
More detail will need to be flushed out on this item in preparation for the March 11 project meeting.

**Comment by bstabler** [comment]
Now that RSG has admin on the repo, @toliwaga will take ownership of the Travis integration and make sure everything is working.  Then we'll add a new test.  We will also write protect the master branch to require automated testing with Travis.

**Comment by danielsclint** [comment]
I added a separate ticket (#64) for the write-protection. It seems like a discrete task in my head.

**Comment by toliwaga** [comment]
This is working now, with travis running tests with --cov-report and after_success notification to coveralls.
