### ISSUE TITLE
pandas 0.18 breaks _check_for_variability

### ISSUE THREAD

**Issue by toliwaga** [UDST/activitysim#63]
DataFrame .describe() treats bool as categorical data in pandas>=0.18 and drops bool columns (unless returns include='all' is passed, in which case std is returned as Nan) so _check_for_variability in activitysim.py fails silently for specs with mixed bool and numeric target values and noisily for specs with only bool targets.

There is an easy fix: convert the bool columns to int in _check_for_variability before calling describe around line 149. But it is slightly tricky in that the sample returned by random_rows is a view into underlying data so the sample rows may need to be copied before assignment. (pandas seems to be a bit unpredictable as to whether it is actually a view or a copy depending on the size of the data. ) 

Come to think of it, this is also presumably broken for string types though there are perhaps no instances of them in specs currently. Certainly not any specs with only string columns so it won't fail noisily.

Alternatively I could handle bool types explicitly and avoid the need to copy data, at the cost of the added complexity of handling different column types explicitly.

**Comment by fscottfoti** [comment]
Hmm, `.astype('int')` would always copy right?  Seems like you could sample the rows and call `.astype('float')` on the whole matrix and check for variability then?  The performance cost would be small and it would accomplish it's goal, I think.  Thoughts?

**Comment by toliwaga** [comment]
I thought column-wise assignment of `.astype('int')` was failing (which confused me since I thought it would copy) but on closer look it does appear to work fine.

**Comment by toliwaga** [comment]
Sorry to be such a dope, but I am new to pandas and obviously confused.

When called from  the test suite, this works:

```
rows = random_rows(model_design, l)
bool_cols = list(rows.columns[ rows.dtypes=='bool' ])
for c in bool_cols:
    rows[c] = rows[c].astype('int')
```

And this doesn’t:

```
rows = random_rows(model_design, l)
bool_cols = list(rows.columns[ rows.dtypes=='bool' ])
rows[ bool_cols ] = rows[ bool_cols ].astype('int’)
```

But the latter works just fine in a little test program running independently. So I concluded that df.take was returning a view on the underlying dataframe. Am I nuts?

**Comment by toliwaga** [comment]
OK, so here is what is really going on.  The second version fails because there are duplicate expressions in the example mandatory_tour_frequency model spec:

And so there are duplicate columns in the eval_variables results (whose columns are named with the expressions used to compute them.)

So columns named  'ptype == 1', 'ptype == 2', each appear twice because they were assigned by spec rows:

This leads to some rather odd behavior when you try to reference the dataframes by column names. Especially as pandas does (different) magic with expressions on the LHS and RHS of assignment operators;

Try executing the following and you will get the idea
```
df = pd.DataFrame.from_items([('dupe', [True, True, True, True]), ('dupe', [False, False, False, False])])
df[['dupe']] = df[['dupe']].astype('int')
```

**Comment by fscottfoti** [comment]
I see - that makes a lot of sense.  In this case
