### ISSUE TITLE
example broken?

### ISSUE THREAD

**Issue by toliwaga** [UDST/activitysim#68]
Ben reports the example/simpulation.py is failing. It is working fine for me on OSX. It may be package version dependent?

@bstabler - could you do a pip freeze and capture output and I will see if I can reproduce.

**Comment by bstabler** [comment]
My pandas was 0.17.1 and your pandas is 0.18.  I just upgraded to 0.18 but now pandas is failing with an numexpr import error.  I think the issue is related to https://github.com/pydata/pandas/issues/12489.  I'm investigating.

**Comment by bstabler** [comment]
An uninstall of numexpr and a new install of numexpr 2.5.1 appears to have worked.  I can now successfully run the example.
