### ISSUE TITLE
mini model test

### ISSUE THREAD

**Issue by bstabler** [UDST/activitysim#71]
The current example and tests use only the distance skim for all skim data and also runs only selective purposes, modes, and other expressions.  This was likely done in part to be fast and to make use of free online Travis CI integration.  In order to continue to flush out the implementation, we'd like to create a mini model test, with say 20 zones, so we can always be working with a more comprehensive test bed.  We did this for the Oregon statewide integrated model and it proved to be extremely useful.  We'll need to select 20 zones that have good coverage for the various input data - land use, mode availability, etc.  We'll also create a script to automatically create the mini model inputs from the full set of inputs.  What do others think about this?

**Comment by bstabler** [comment]
@DavidOry suggested a zone 1-190 (SF county) test.  The group agreed to give this a try.

**Comment by bstabler** [comment]
@toliwaga to test once the full set of skims revisions are in place.  I tested these on the current limited example and they worked fine.

**Comment by toliwaga** [comment]
This is all working fine on the large-scale-test branch. Tidying things up to merge into master...

**Comment by bstabler** [comment]
We also created a 25 zone version for the Travis testing and plan to use this as the example and main test moving forward.
