### ISSUE TITLE
destination not defined for mandatory_tours

### ISSUE THREAD

**Issue by toliwaga** [UDST/activitysim#73]
destination_choice assigns destination taz for non mandatory tours.

destination is implicitly workplace_taz for work tours and school_taz for school taz, but the destination fields are never set, breaking a bunch of computed columns like dest_topology that are used by the mode_choice_simulate spec - they come up as NaN values resulting in Nan utilities that  causes the make_choices call to fail in simple_simulate.

This is not caught in testing as mode_choice_simulate in master only runs tour_type 'eatout' which is a non mandatory tour type and thus has a valid destination.

I am holding on fixing this because it depends on several cascading shortcuts int the  current implementation that we will want to address at once, and I don't want to add a fix until first writing a failing test...

**Comment by toliwaga** [comment]
This is now fixed in the large-scale-test branch but not yet merged into master. Fixing the various interrelated skim issues requires new test dataset or it runs too slow and too big for travis. Removing hte single-skim hack drove the need for a smaller (190 TAZ) sample data set, which in turn requires some updates to the installation documentation. I am holding off merging for a another day or two in order not to break the documentation on master branch.

**Comment by bstabler** [comment]
documentation updated
