### ISSUE TITLE
should implement logging

### ISSUE THREAD

**Issue by toliwaga** [UDST/activitysim#87]
It would be very useful to have python logging with log levels, redirection, etc.

**Comment by bstabler** [comment]
[Team agreed to start this](https://github.com/UDST/activitysim/wiki/Project-Meeting-2016.05.06) as part of [Task 9](https://github.com/UDST/activitysim/wiki/Phase-2-Scope-of-Work#task-9-tracing-choice-results-of-households-and-persons)

**Comment by bstabler** [comment]
We'll need to update the documentation and example as well once this is implemented

**Comment by toliwaga** [comment]
I am working implementing standard python logging with facility for user to configure log levels, file output, etc from logging.yaml file in configs dir.

Currently going through and replacing most existing print statements with logger calls with appropriate severity levels, etc.

**Comment by bstabler** [comment]
Team agrees logging looks good - https://github.com/UDST/activitysim/wiki/Project-Meeting-2016.06.15
