### ISSUE TITLE
tracing requirements

### ISSUE THREAD

**Issue by bstabler** [UDST/activitysim#92]
we're going to implement tracing in addition to logging (#87) since we need this feature to track down data and expression errors related to #81.  What are the requirements for this functionality?

We discussed this on our call [today](https://github.com/UDST/activitysim/wiki/Project-Meeting-2016.05.20) and came up with the following list:
  - easy to parse text format such as CSV
  - easy to import into Excel since this is the tool most users will use for exploring the traced results
  - maybe two outputs - one big log file like CT-RAMP does today so you can see relationships between sub-model data and expressions, and then a CSV file for each sub-model?
  - user will specify one HH ID to trace
  - output information will be similar to what CT-RAMP produces

**Comment by bstabler** [comment]
Team agrees tracing generally looks good - https://github.com/UDST/activitysim/wiki/Project-Meeting-2016.06.15

Here are a couple bugs/issues to fix:
  - make sure all tables have headers
  - make sure each model has a model design table with expressions and solved value

Some improvements for the future:
 - joined views of tables for easier use
 - add source table column to make manual joins of tables easier
  - create an external post-processor to create better reports for each model
  - take this version of tracing from raw data to beautiful reports
  - print labels instead of codes - such as person type 2 is worker; add print methods for data items

**Comment by toliwaga** [comment]
When dumping interaction_simulate model_design, it is kind of awkward to makes sense of the dumped dataframe when there are multiple persons in the traced households and they have different alternatives. 

I think it might be more useful to create a separate csv file for each individual in the household so the alternative columns all mean the same thing. We can add a row to the file listing the alternative (d.g. TAZ) for each column.

I pushed a version that works like this hh-trace branch.

**Comment by bstabler** [comment]
the example outputs looks good and maintain the requirement that they are easy to parse with a Python or R-type script.  Please merge this into the master.  Thanks.
